"""create companies and financial reports

Revision ID: 32a0f24006ed
Revises: 
Create Date: 2026-07-20 07:12:49.669812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a0f24006ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('business_type', sa.String(length=60), server_default='other', nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('tin', sa.String(length=100), nullable=True),
    sa.Column('ghana_card_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('default_currency', sa.String(length=3), server_default='GHS', nullable=False),
    sa.Column('reporting_basis', sa.String(length=80), server_default='accrual', nullable=False),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_business_type'), ['business_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_tin'), ['tin'], unique=False)

    op.create_table('financial_reports',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('comparison_report_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=60), server_default='annual_financial_statements', nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('financial_year', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='GHS', nullable=False),
    sa.Column('business_template', sa.String(length=60), server_default='other', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('accountant_report_text', sa.Text(), nullable=True),
    sa.Column('finalised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_financial_reports_period_dates')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_financial_reports_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comparison_report_id'], ['financial_reports.id'], name=op.f('fk_financial_reports_comparison_report_id_financial_reports'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_reports'))
    )
    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_reports_business_template'), ['business_template'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_comparison_report_id'), ['comparison_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_financial_year'), ['financial_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_reports_title'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_status'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_financial_year'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_comparison_report_id'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_company_id'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_business_template'))

    op.drop_table('financial_reports')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_tin'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_is_active'))
        batch_op.drop_index(batch_op.f('ix_companies_business_type'))

    op.drop_table('companies')
    # ### end Alembic commands ###
