"""add cash equivalent flag to ledger accounts

Revision ID: 40d54e1448ff
Revises: 776eab6dc089
Create Date: 2026-07-22 14:30:54.398056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d54e1448ff'
down_revision: Union[str, Sequence[str], None] = '776eab6dc089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cash_equivalent', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_ledger_accounts_is_cash_equivalent'), ['is_cash_equivalent'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_is_cash_equivalent'))
        batch_op.drop_column('is_cash_equivalent')

    # ### end Alembic commands ###
