"""add complete report package metadata

Revision ID: 4ece39e73969
Revises: abbf66f9e8dd
Create Date: 2026-08-20 15:00:18.387604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ece39e73969'
down_revision: Union[str, Sequence[str], None] = 'abbf66f9e8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_name', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('principal_title', sa.String(length=120), nullable=True))

    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accountant_firm_name', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('accountant_professional_designation', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('accountant_firm_address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.drop_column('accountant_firm_address')
        batch_op.drop_column('accountant_professional_designation')
        batch_op.drop_column('accountant_firm_name')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('principal_title')
        batch_op.drop_column('principal_name')

    # ### end Alembic commands ###
