"""create notes and disclosure templates

Revision ID: 711a7787d700
Revises: 40d54e1448ff
Create Date: 2026-07-25 20:08:48.517672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711a7787d700'
down_revision: Union[str, Sequence[str], None] = '40d54e1448ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disclosure_templates',
    sa.Column('template_key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('note_type', sa.String(length=60), server_default='general_disclosure', nullable=False),
    sa.Column('statement_name', sa.String(length=60), nullable=True),
    sa.Column('statement_line_key', sa.String(length=100), nullable=True),
    sa.Column('default_content', sa.Text(), server_default='', nullable=False),
    sa.Column('is_system_template', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_disclosure_templates_display_order_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disclosure_templates')),
    sa.UniqueConstraint('template_key', name='template_key_unique')
    )
    with op.batch_alter_table('disclosure_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disclosure_templates_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosure_templates_is_required'), ['is_required'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosure_templates_is_system_template'), ['is_system_template'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosure_templates_note_type'), ['note_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosure_templates_statement_line_key'), ['statement_line_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosure_templates_statement_name'), ['statement_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosure_templates_template_key'), ['template_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_disclosure_templates_title'), ['title'], unique=False)

    op.create_table('financial_report_notes',
    sa.Column('financial_report_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('note_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('note_type', sa.String(length=60), server_default='general_disclosure', nullable=False),
    sa.Column('statement_name', sa.String(length=60), nullable=True),
    sa.Column('statement_line_key', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('note_number > 0', name=op.f('ck_financial_report_notes_note_number_positive')),
    sa.ForeignKeyConstraint(['financial_report_id'], ['financial_reports.id'], name=op.f('fk_financial_report_notes_financial_report_id_financial_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['disclosure_templates.id'], name=op.f('fk_financial_report_notes_template_id_disclosure_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_report_notes')),
    sa.UniqueConstraint('financial_report_id', 'note_number', name='report_note_number')
    )
    with op.batch_alter_table('financial_report_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_report_notes_financial_report_id'), ['financial_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_report_notes_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_report_notes_note_number'), ['note_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_report_notes_note_type'), ['note_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_report_notes_statement_line_key'), ['statement_line_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_report_notes_statement_name'), ['statement_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_report_notes_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_report_notes_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_report_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_report_notes_title'))
        batch_op.drop_index(batch_op.f('ix_financial_report_notes_template_id'))
        batch_op.drop_index(batch_op.f('ix_financial_report_notes_statement_name'))
        batch_op.drop_index(batch_op.f('ix_financial_report_notes_statement_line_key'))
        batch_op.drop_index(batch_op.f('ix_financial_report_notes_note_type'))
        batch_op.drop_index(batch_op.f('ix_financial_report_notes_note_number'))
        batch_op.drop_index(batch_op.f('ix_financial_report_notes_is_active'))
        batch_op.drop_index(batch_op.f('ix_financial_report_notes_financial_report_id'))

    op.drop_table('financial_report_notes')
    with op.batch_alter_table('disclosure_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disclosure_templates_title'))
        batch_op.drop_index(batch_op.f('ix_disclosure_templates_template_key'))
        batch_op.drop_index(batch_op.f('ix_disclosure_templates_statement_name'))
        batch_op.drop_index(batch_op.f('ix_disclosure_templates_statement_line_key'))
        batch_op.drop_index(batch_op.f('ix_disclosure_templates_note_type'))
        batch_op.drop_index(batch_op.f('ix_disclosure_templates_is_system_template'))
        batch_op.drop_index(batch_op.f('ix_disclosure_templates_is_required'))
        batch_op.drop_index(batch_op.f('ix_disclosure_templates_is_active'))

    op.drop_table('disclosure_templates')
    # ### end Alembic commands ###
