"""create journal entries and lines

Revision ID: 776eab6dc089
Revises: 9bb95ea5f317
Create Date: 2026-07-20 11:34:05.433412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776eab6dc089'
down_revision: Union[str, Sequence[str], None] = '9bb95ea5f317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('financial_report_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('entry_number', sa.String(length=40), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), server_default='standard', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('source', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('sequence_number > 0', name=op.f('ck_journal_entries_sequence_number_positive')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_journal_entries_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_report_id'], ['financial_reports.id'], name=op.f('fk_journal_entries_financial_report_id_financial_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries')),
    sa.UniqueConstraint('financial_report_id', 'entry_number', name='report_entry_number'),
    sa.UniqueConstraint('financial_report_id', 'sequence_number', name='report_sequence_number')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_number'), ['entry_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_financial_report_id'), ['financial_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_status'), ['status'], unique=False)

    op.create_table('journal_lines',
    sa.Column('journal_entry_id', sa.String(length=36), nullable=False),
    sa.Column('ledger_account_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)', name=op.f('ck_journal_lines_exactly_one_amount_side')),
    sa.CheckConstraint('credit >= 0', name=op.f('ck_journal_lines_credit_non_negative')),
    sa.CheckConstraint('debit >= 0', name=op.f('ck_journal_lines_debit_non_negative')),
    sa.CheckConstraint('line_number > 0', name=op.f('ck_journal_lines_line_number_positive')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_journal_lines_journal_entry_id_journal_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledger_accounts.id'], name=op.f('fk_journal_lines_ledger_account_id_ledger_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_lines')),
    sa.UniqueConstraint('journal_entry_id', 'line_number', name='entry_line_number')
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_journal_entry_id'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_ledger_account_id'), ['ledger_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_ledger_account_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_journal_entry_id'))

    op.drop_table('journal_lines')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_status'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_source'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_reference'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_financial_report_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_type'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_number'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_date'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_company_id'))

    op.drop_table('journal_entries')
    # ### end Alembic commands ###
