"""create ledger accounts

Revision ID: 9bb95ea5f317
Revises: 32a0f24006ed
Create Date: 2026-07-20 10:07:20.084305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb95ea5f317'
down_revision: Union[str, Sequence[str], None] = '32a0f24006ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_accounts',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('parent_account_id', sa.String(length=36), nullable=True),
    sa.Column('account_code', sa.String(length=30), nullable=False),
    sa.Column('account_name', sa.String(length=180), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('report_category', sa.String(length=60), nullable=False),
    sa.Column('cash_flow_category', sa.String(length=30), nullable=True),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_account', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_ledger_accounts_display_order_non_negative')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ledger_accounts_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_account_id'], ['ledger_accounts.id'], name=op.f('fk_ledger_accounts_parent_account_id_ledger_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_accounts')),
    sa.UniqueConstraint('company_id', 'account_code', name='company_account_code')
    )
    with op.batch_alter_table('ledger_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_accounts_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_account_name'), ['account_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_cash_flow_category'), ['cash_flow_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_is_system_account'), ['is_system_account'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_parent_account_id'), ['parent_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_accounts_report_category'), ['report_category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_report_category'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_parent_account_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_is_system_account'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_is_active'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_company_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_cash_flow_category'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_account_type'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_account_name'))
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_account_code'))

    op.drop_table('ledger_accounts')
    # ### end Alembic commands ###
