"""create tax profiles rules and calculations

Revision ID: abbf66f9e8dd
Revises: b08d5d942f85
Create Date: 2026-07-27 21:22:23.107194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbf66f9e8dd'
down_revision: Union[str, Sequence[str], None] = 'b08d5d942f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_profiles',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('profile_code', sa.String(length=60), nullable=False),
    sa.Column('profile_name', sa.String(length=180), nullable=False),
    sa.Column('jurisdiction_country_code', sa.String(length=2), server_default='GH', nullable=False),
    sa.Column('jurisdiction_name', sa.String(length=120), server_default='Ghana', nullable=False),
    sa.Column('tax_identifier', sa.String(length=120), nullable=True),
    sa.Column('taxpayer_category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_tax_profiles_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_profiles')),
    sa.UniqueConstraint('company_id', 'profile_code', name='company_tax_profile_code'),
    sa.UniqueConstraint('company_id', 'profile_name', name='company_tax_profile_name')
    )
    with op.batch_alter_table('tax_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_profiles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_profiles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_profiles_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_profiles_jurisdiction_country_code'), ['jurisdiction_country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_profiles_profile_code'), ['profile_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_profiles_profile_name'), ['profile_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_profiles_tax_identifier'), ['tax_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_profiles_taxpayer_category'), ['taxpayer_category'], unique=False)

    op.create_table('tax_rules',
    sa.Column('tax_profile_id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('tax_type', sa.String(length=80), nullable=False),
    sa.Column('calculation_method', sa.String(length=30), nullable=False),
    sa.Column('rate_percentage', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='GHS', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('taxpayer_category', sa.String(length=120), nullable=True),
    sa.Column('business_activity', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_system_rule', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(calculation_method = 'percentage' AND rate_percentage IS NOT NULL AND fixed_amount IS NULL) OR (calculation_method = 'fixed_amount' AND fixed_amount IS NOT NULL AND rate_percentage IS NULL)", name=op.f('ck_tax_rules_calculation_value_matches_method')),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_tax_rules_display_order_non_negative')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_tax_rules_effective_dates')),
    sa.CheckConstraint('fixed_amount IS NULL OR fixed_amount >= 0', name=op.f('ck_tax_rules_fixed_amount_non_negative')),
    sa.CheckConstraint('rate_percentage IS NULL OR (rate_percentage >= 0 AND rate_percentage <= 100)', name=op.f('ck_tax_rules_percentage_range')),
    sa.ForeignKeyConstraint(['tax_profile_id'], ['tax_profiles.id'], name=op.f('fk_tax_rules_tax_profile_id_tax_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_rules')),
    sa.UniqueConstraint('tax_profile_id', 'rule_code', 'effective_from', name='profile_rule_effective_date')
    )
    with op.batch_alter_table('tax_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_rules_business_activity'), ['business_activity'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_calculation_method'), ['calculation_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_effective_to'), ['effective_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_is_system_rule'), ['is_system_rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_rule_code'), ['rule_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_rule_name'), ['rule_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_tax_profile_id'), ['tax_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_tax_type'), ['tax_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_taxpayer_category'), ['taxpayer_category'], unique=False)

    op.create_table('tax_calculations',
    sa.Column('financial_report_id', sa.String(length=36), nullable=False),
    sa.Column('tax_rule_id', sa.String(length=36), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('tax_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='GHS', nullable=False),
    sa.Column('rule_code_snapshot', sa.String(length=100), nullable=False),
    sa.Column('rule_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('tax_type_snapshot', sa.String(length=80), nullable=False),
    sa.Column('calculation_method_snapshot', sa.String(length=30), nullable=False),
    sa.Column('rate_applied', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('fixed_amount_applied', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('calculation_details_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('fixed_amount_applied IS NULL OR fixed_amount_applied >= 0', name=op.f('ck_tax_calculations_fixed_amount_applied_non_negative')),
    sa.CheckConstraint('rate_applied IS NULL OR (rate_applied >= 0 AND rate_applied <= 100)', name=op.f('ck_tax_calculations_rate_applied_range')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_tax_calculations_tax_amount_non_negative')),
    sa.ForeignKeyConstraint(['financial_report_id'], ['financial_reports.id'], name=op.f('fk_tax_calculations_financial_report_id_financial_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_rule_id'], ['tax_rules.id'], name=op.f('fk_tax_calculations_tax_rule_id_tax_rules'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_calculations'))
    )
    with op.batch_alter_table('tax_calculations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_calculations_calculation_date'), ['calculation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_calculations_financial_report_id'), ['financial_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_calculations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_calculations_tax_rule_id'), ['tax_rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_calculations_tax_type_snapshot'), ['tax_type_snapshot'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_calculations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_calculations_tax_type_snapshot'))
        batch_op.drop_index(batch_op.f('ix_tax_calculations_tax_rule_id'))
        batch_op.drop_index(batch_op.f('ix_tax_calculations_status'))
        batch_op.drop_index(batch_op.f('ix_tax_calculations_financial_report_id'))
        batch_op.drop_index(batch_op.f('ix_tax_calculations_calculation_date'))

    op.drop_table('tax_calculations')
    with op.batch_alter_table('tax_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_rules_taxpayer_category'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_tax_type'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_tax_profile_id'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_status'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_rule_name'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_rule_code'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_is_system_rule'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_effective_to'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_effective_from'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_calculation_method'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_business_activity'))

    op.drop_table('tax_rules')
    with op.batch_alter_table('tax_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_profiles_taxpayer_category'))
        batch_op.drop_index(batch_op.f('ix_tax_profiles_tax_identifier'))
        batch_op.drop_index(batch_op.f('ix_tax_profiles_profile_name'))
        batch_op.drop_index(batch_op.f('ix_tax_profiles_profile_code'))
        batch_op.drop_index(batch_op.f('ix_tax_profiles_jurisdiction_country_code'))
        batch_op.drop_index(batch_op.f('ix_tax_profiles_is_default'))
        batch_op.drop_index(batch_op.f('ix_tax_profiles_is_active'))
        batch_op.drop_index(batch_op.f('ix_tax_profiles_company_id'))

    op.drop_table('tax_profiles')
    # ### end Alembic commands ###
