"""add report finalisation versioning

Revision ID: b08d5d942f85
Revises: 711a7787d700
Create Date: 2026-07-26 11:10:36.787628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08d5d942f85'
down_revision: Union[str, Sequence[str], None] = '711a7787d700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_report_versions',
    sa.Column('financial_report_id', sa.String(length=36), nullable=False),
    sa.Column('revision_series_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('finalised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalised_by', sa.String(length=180), nullable=False),
    sa.Column('accountant_name', sa.String(length=180), nullable=False),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('snapshot_checksum', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revision_number > 0', name=op.f('ck_financial_report_versions_revision_number_positive')),
    sa.ForeignKeyConstraint(['financial_report_id'], ['financial_reports.id'], name=op.f('fk_financial_report_versions_financial_report_id_financial_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_report_versions')),
    sa.UniqueConstraint('financial_report_id', name='financial_report_final_version'),
    sa.UniqueConstraint('revision_series_id', 'revision_number', name='report_series_revision')
    )
    with op.batch_alter_table('financial_report_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_report_versions_finalised_at'), ['finalised_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_report_versions_financial_report_id'), ['financial_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_report_versions_revision_series_id'), ['revision_series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_report_versions_snapshot_checksum'), ['snapshot_checksum'], unique=False)

    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision_series_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('revision_number', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('supersedes_report_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('revision_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('accountant_name', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('finalised_by', sa.String(length=180), nullable=True))
        batch_op.create_index(batch_op.f('ix_financial_reports_revision_number'), ['revision_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_revision_series_id'), ['revision_series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_reports_supersedes_report_id'), ['supersedes_report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_reports_supersedes_report_id'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_revision_series_id'))
        batch_op.drop_index(batch_op.f('ix_financial_reports_revision_number'))
        batch_op.drop_column('finalised_by')
        batch_op.drop_column('accountant_name')
        batch_op.drop_column('revision_reason')
        batch_op.drop_column('supersedes_report_id')
        batch_op.drop_column('revision_number')
        batch_op.drop_column('revision_series_id')

    with op.batch_alter_table('financial_report_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_report_versions_snapshot_checksum'))
        batch_op.drop_index(batch_op.f('ix_financial_report_versions_revision_series_id'))
        batch_op.drop_index(batch_op.f('ix_financial_report_versions_financial_report_id'))
        batch_op.drop_index(batch_op.f('ix_financial_report_versions_finalised_at'))

    op.drop_table('financial_report_versions')
    # ### end Alembic commands ###
