"""add cash equivalent flag to ledger accounts

Revision ID: ba4570dbdbe1
Revises: 40d54e1448ff
Create Date: 2026-07-22 22:33:34.917362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4570dbdbe1'
down_revision: Union[str, Sequence[str], None] = '40d54e1448ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
