from dataclasses import dataclass

from app.schemas.company import BusinessType
from app.schemas.ledger_account import (
    AccountType,
    CashFlowCategory,
    NormalBalance,
    ReportCategory,
)


@dataclass(frozen=True, slots=True)
class AccountTemplateItem:
    """One account definition used when initializing a company."""

    account_code: str
    account_name: str
    account_type: AccountType
    report_category: ReportCategory
    normal_balance: NormalBalance
    cash_flow_category: CashFlowCategory | None
    display_order: int
    description: str | None = None


BASE_ACCOUNTS: tuple[AccountTemplateItem, ...] = (
    AccountTemplateItem(
        "1000",
        "Cash in Hand",
        AccountType.ASSET,
        ReportCategory.CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        1000,
    ),
    AccountTemplateItem(
        "1010",
        "Bank Accounts",
        AccountType.ASSET,
        ReportCategory.CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        1010,
    ),
    AccountTemplateItem(
        "1020",
        "Mobile Money Balance",
        AccountType.ASSET,
        ReportCategory.CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        1020,
    ),
    AccountTemplateItem(
        "1100",
        "Accounts Receivable",
        AccountType.ASSET,
        ReportCategory.CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        1100,
    ),
    AccountTemplateItem(
        "1110",
        "Allowance for Doubtful Debts",
        AccountType.ASSET,
        ReportCategory.CURRENT_ASSETS,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        1110,
        "Contra-asset account reducing accounts receivable.",
    ),
    AccountTemplateItem(
        "1300",
        "Prepayments",
        AccountType.ASSET,
        ReportCategory.CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        1300,
    ),
    AccountTemplateItem(
        "1500",
        "Motor Vehicles",
        AccountType.ASSET,
        ReportCategory.NON_CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.INVESTING,
        1500,
    ),
    AccountTemplateItem(
        "1510",
        "Furniture and Fittings",
        AccountType.ASSET,
        ReportCategory.NON_CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.INVESTING,
        1510,
    ),
    AccountTemplateItem(
        "1520",
        "Equipment",
        AccountType.ASSET,
        ReportCategory.NON_CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.INVESTING,
        1520,
    ),
    AccountTemplateItem(
        "1590",
        "Accumulated Depreciation",
        AccountType.ASSET,
        ReportCategory.NON_CURRENT_ASSETS,
        NormalBalance.CREDIT,
        CashFlowCategory.NON_CASH,
        1590,
        "Contra-asset account reducing property, plant and equipment.",
    ),
    AccountTemplateItem(
        "2000",
        "Accounts Payable",
        AccountType.LIABILITY,
        ReportCategory.CURRENT_LIABILITIES,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        2000,
    ),
    AccountTemplateItem(
        "2010",
        "Accrued Expenses",
        AccountType.LIABILITY,
        ReportCategory.CURRENT_LIABILITIES,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        2010,
    ),
    AccountTemplateItem(
        "2020",
        "Tax Payable",
        AccountType.LIABILITY,
        ReportCategory.CURRENT_LIABILITIES,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        2020,
    ),
    AccountTemplateItem(
        "2100",
        "Short-Term Loans",
        AccountType.LIABILITY,
        ReportCategory.CURRENT_LIABILITIES,
        NormalBalance.CREDIT,
        CashFlowCategory.FINANCING,
        2100,
    ),
    AccountTemplateItem(
        "2500",
        "Long-Term Loans",
        AccountType.LIABILITY,
        ReportCategory.NON_CURRENT_LIABILITIES,
        NormalBalance.CREDIT,
        CashFlowCategory.FINANCING,
        2500,
    ),
    AccountTemplateItem(
        "3000",
        "Owner's Capital",
        AccountType.EQUITY,
        ReportCategory.EQUITY,
        NormalBalance.CREDIT,
        CashFlowCategory.FINANCING,
        3000,
    ),
    AccountTemplateItem(
        "3010",
        "Drawings",
        AccountType.EQUITY,
        ReportCategory.EQUITY,
        NormalBalance.DEBIT,
        CashFlowCategory.FINANCING,
        3010,
    ),
    AccountTemplateItem(
        "3020",
        "Retained Earnings",
        AccountType.EQUITY,
        ReportCategory.EQUITY,
        NormalBalance.CREDIT,
        CashFlowCategory.NOT_APPLICABLE,
        3020,
    ),
    AccountTemplateItem(
        "4900",
        "Other Income",
        AccountType.REVENUE,
        ReportCategory.OTHER_INCOME,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4900,
    ),
    AccountTemplateItem(
        "7000",
        "Salaries and Wages",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7000,
    ),
    AccountTemplateItem(
        "7010",
        "Rent Expense",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7010,
    ),
    AccountTemplateItem(
        "7020",
        "Utilities",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7020,
    ),
    AccountTemplateItem(
        "7030",
        "Insurance Expense",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7030,
    ),
    AccountTemplateItem(
        "7040",
        "Repairs and Maintenance",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7040,
    ),
    AccountTemplateItem(
        "7050",
        "Depreciation Expense",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.NON_CASH,
        7050,
    ),
    AccountTemplateItem(
        "7060",
        "Professional Fees",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7060,
    ),
    AccountTemplateItem(
        "7070",
        "Office Expenses",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7070,
    ),
    AccountTemplateItem(
        "7080",
        "Bank Charges",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7080,
    ),
    AccountTemplateItem(
        "7090",
        "Telephone and Internet",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7090,
    ),
    AccountTemplateItem(
        "7100",
        "Travel and Transport",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7100,
    ),
    AccountTemplateItem(
        "7110",
        "Marketing and Advertising",
        AccountType.EXPENSE,
        ReportCategory.SELLING_DISTRIBUTION_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7110,
    ),
    AccountTemplateItem(
        "7120",
        "Bad Debt Expense",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.NON_CASH,
        7120,
    ),
    AccountTemplateItem(
        "7190",
        "Miscellaneous Expenses",
        AccountType.EXPENSE,
        ReportCategory.ADMINISTRATIVE_EXPENSES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        7190,
    ),
    AccountTemplateItem(
        "8000",
        "Finance Costs",
        AccountType.EXPENSE,
        ReportCategory.FINANCE_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        8000,
    ),
    AccountTemplateItem(
        "9000",
        "Income Tax Expense",
        AccountType.EXPENSE,
        ReportCategory.TAXATION,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        9000,
    ),
)


TRADING_ACCOUNTS: tuple[AccountTemplateItem, ...] = (
    AccountTemplateItem(
        "1200",
        "Inventory",
        AccountType.ASSET,
        ReportCategory.CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        1200,
    ),
    AccountTemplateItem(
        "4000",
        "Sales Revenue",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4000,
    ),
    AccountTemplateItem(
        "4010",
        "Sales Returns",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        4010,
    ),
    AccountTemplateItem(
        "5000",
        "Opening Inventory",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5000,
    ),
    AccountTemplateItem(
        "5010",
        "Purchases",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5010,
    ),
    AccountTemplateItem(
        "5020",
        "Carriage Inward",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5020,
    ),
    AccountTemplateItem(
        "5030",
        "Purchase Returns",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        5030,
    ),
    AccountTemplateItem(
        "5040",
        "Closing Inventory Adjustment",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        5040,
    ),
)


SERVICE_ACCOUNTS: tuple[AccountTemplateItem, ...] = (
    AccountTemplateItem(
        "4000",
        "Service Revenue",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4000,
    ),
    AccountTemplateItem(
        "5000",
        "Direct Labour",
        AccountType.EXPENSE,
        ReportCategory.DIRECT_SERVICE_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5000,
    ),
    AccountTemplateItem(
        "5010",
        "Subcontractor Costs",
        AccountType.EXPENSE,
        ReportCategory.DIRECT_SERVICE_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5010,
    ),
    AccountTemplateItem(
        "5020",
        "Direct Service Expenses",
        AccountType.EXPENSE,
        ReportCategory.DIRECT_SERVICE_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5020,
    ),
)


MANUFACTURING_ACCOUNTS: tuple[
    AccountTemplateItem,
    ...,
] = (
    AccountTemplateItem(
        "1200",
        "Raw Materials Inventory",
        AccountType.ASSET,
        ReportCategory.CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        1200,
    ),
    AccountTemplateItem(
        "1210",
        "Work in Progress",
        AccountType.ASSET,
        ReportCategory.CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        1210,
    ),
    AccountTemplateItem(
        "1220",
        "Finished Goods Inventory",
        AccountType.ASSET,
        ReportCategory.CURRENT_ASSETS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        1220,
    ),
    AccountTemplateItem(
        "4000",
        "Sales Revenue",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4000,
    ),
    AccountTemplateItem(
        "5000",
        "Raw Materials Used",
        AccountType.EXPENSE,
        ReportCategory.MANUFACTURING_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5000,
    ),
    AccountTemplateItem(
        "5010",
        "Direct Factory Labour",
        AccountType.EXPENSE,
        ReportCategory.MANUFACTURING_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5010,
    ),
    AccountTemplateItem(
        "5020",
        "Factory Overheads",
        AccountType.EXPENSE,
        ReportCategory.MANUFACTURING_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5020,
    ),
    AccountTemplateItem(
        "5030",
        "Cost of Production",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5030,
    ),
)


TRANSPORT_ACCOUNTS: tuple[AccountTemplateItem, ...] = (
    AccountTemplateItem(
        "4000",
        "Transport Income",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4000,
    ),
    AccountTemplateItem(
        "4010",
        "Delivery Income",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4010,
    ),
    AccountTemplateItem(
        "5000",
        "Fuel and Lubricants",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5000,
    ),
    AccountTemplateItem(
        "5010",
        "Driver Wages",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5010,
    ),
    AccountTemplateItem(
        "5020",
        "Vehicle Repairs",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5020,
    ),
    AccountTemplateItem(
        "5030",
        "Road Tolls and Licensing",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5030,
    ),
    AccountTemplateItem(
        "5040",
        "Vehicle Insurance",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5040,
    ),
    AccountTemplateItem(
        "5050",
        "Vehicle Depreciation",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.NON_CASH,
        5050,
    ),
)


CHURCH_ACCOUNTS: tuple[AccountTemplateItem, ...] = (
    AccountTemplateItem(
        "4000",
        "Tithes",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4000,
    ),
    AccountTemplateItem(
        "4010",
        "Offerings",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4010,
    ),
    AccountTemplateItem(
        "4020",
        "Donations",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4020,
    ),
    AccountTemplateItem(
        "4030",
        "Grants",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4030,
    ),
    AccountTemplateItem(
        "5000",
        "Programme Expenses",
        AccountType.EXPENSE,
        ReportCategory.DIRECT_SERVICE_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5000,
    ),
    AccountTemplateItem(
        "5010",
        "Welfare Expenses",
        AccountType.EXPENSE,
        ReportCategory.DIRECT_SERVICE_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5010,
    ),
    AccountTemplateItem(
        "5020",
        "Missions and Outreach",
        AccountType.EXPENSE,
        ReportCategory.DIRECT_SERVICE_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5020,
    ),
)


SCHOOL_ACCOUNTS: tuple[AccountTemplateItem, ...] = (
    AccountTemplateItem(
        "4000",
        "Tuition Fees",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4000,
    ),
    AccountTemplateItem(
        "4010",
        "Admission Fees",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4010,
    ),
    AccountTemplateItem(
        "4020",
        "Boarding Fees",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4020,
    ),
    AccountTemplateItem(
        "4030",
        "Other School Income",
        AccountType.REVENUE,
        ReportCategory.OTHER_INCOME,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4030,
    ),
    AccountTemplateItem(
        "5000",
        "Teaching Staff Costs",
        AccountType.EXPENSE,
        ReportCategory.DIRECT_SERVICE_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5000,
    ),
    AccountTemplateItem(
        "5010",
        "Teaching Materials",
        AccountType.EXPENSE,
        ReportCategory.DIRECT_SERVICE_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5010,
    ),
    AccountTemplateItem(
        "5020",
        "Student Welfare",
        AccountType.EXPENSE,
        ReportCategory.DIRECT_SERVICE_COSTS,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5020,
    ),
)


OTHER_ACCOUNTS: tuple[AccountTemplateItem, ...] = (
    AccountTemplateItem(
        "4000",
        "Revenue",
        AccountType.REVENUE,
        ReportCategory.REVENUE,
        NormalBalance.CREDIT,
        CashFlowCategory.OPERATING,
        4000,
    ),
    AccountTemplateItem(
        "5000",
        "Direct Costs",
        AccountType.EXPENSE,
        ReportCategory.COST_OF_SALES,
        NormalBalance.DEBIT,
        CashFlowCategory.OPERATING,
        5000,
    ),
)


BUSINESS_ACCOUNT_TEMPLATES: dict[
    BusinessType,
    tuple[AccountTemplateItem, ...],
] = {
    BusinessType.TRADING: TRADING_ACCOUNTS,
    BusinessType.RETAIL: TRADING_ACCOUNTS,
    BusinessType.SERVICE: SERVICE_ACCOUNTS,
    BusinessType.MANUFACTURING: MANUFACTURING_ACCOUNTS,
    BusinessType.TRANSPORT_LOGISTICS: TRANSPORT_ACCOUNTS,
    BusinessType.CHURCH_NONPROFIT: CHURCH_ACCOUNTS,
    BusinessType.SCHOOL: SCHOOL_ACCOUNTS,
    BusinessType.OTHER: OTHER_ACCOUNTS,
}


def get_account_template(
    business_type: BusinessType,
) -> tuple[AccountTemplateItem, ...]:
    """
    Return common accounts plus accounts for the selected business type.
    """

    template_accounts = BUSINESS_ACCOUNT_TEMPLATES.get(
        business_type,
        OTHER_ACCOUNTS,
    )

    merged_accounts: dict[str, AccountTemplateItem] = {
        account.account_code: account
        for account in BASE_ACCOUNTS
    }

    for account in template_accounts:
        merged_accounts[account.account_code] = account

    return tuple(
        sorted(
            merged_accounts.values(),
            key=lambda account: (
                account.display_order,
                account.account_code,
            ),
        ),
    )